# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.8.9.dev0+gc003429.d20230209'
__version_tuple__ = version_tuple = (0, 8, 9, 'dev0', 'gc003429.d20230209')
