# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.9.dev1+gbcb22b4.d20220912'
__version_tuple__ = version_tuple = (0, 1, 9, 'dev1', 'gbcb22b4.d20220912')
