# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.5.dev0+g19273f0.d20220915'
__version_tuple__ = version_tuple = (0, 2, 5, 'dev0', 'g19273f0.d20220915')
