#!/bin/bash

if [ -d "build" ]; then
    echo "Cleaning previousally generated build files..."
    rm -rfv build
    rm -rfv wrfplot.egg-info
fi

echo "Generating version information..."
echo -e "# Generated by wrfplot build file. Do not edit it manually...\n__version__ = version = '$(setuptools-git-versioning)'" > _version.py

python -m build --sdist

echo "Cleaning build time egg info directory..."
rm -rfv wrfplot.egg-info
